CATEGORY_NAME_MAX_LENGTH = 200
GROUP_NAME_MAX_LENGTH = 100
EXPENSE_DESCRIPTION_MAX_LENGTH = 200
EXPENSE_TOTAL_AMOUNT_MAX_DIGIT = 10
EXPENSES_CATEGORY_DEFAULT = 1
USER_EXPENSE_AMOUNT_MAX_DIGIT = 10
USER_EXPENSE_AMOUNT_DECIMAL_PLACES = 2
